				 
<div class="tab-pane active" id="tab_0">
	<div class="portlet box green">
		<div class="portlet-title">
			<div class="caption">
				<i class="fa fa-reorder"></i>Add New Product
			</div>
			<div class="tools">
				<a href="javascript:;" class="collapse">
				</a>
				<a href="#portlet-config" data-toggle="modal" class="config">
				</a>
				<a href="javascript:;" class="reload">
				</a>
				<a href="javascript:;" class="remove">
				</a>
			</div>
		</div>
		<div class="portlet-body form">
			<!-- BEGIN FORM-->
			<form action="#" class="form-horizontal">
				<div class="form-body">
					<div class="form-group">
						<label class="col-md-4 control-label">Code</label>
						<div class="col-md-4">
							<input type="text" class="form-control" placeholder="Enter Code">
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-4 control-label">Name</label>
						<div class="col-md-4">
							<input type="text" class="form-control" placeholder="Enter Product Name">
						</div>
					</div>

					<div class="form-group">
						<label class="col-md-4 control-label">Brand</label>
						<div class="col-md-4">
							<select class="select_role form-control" data-placeholder="Choose a Brand" tabindex="1">
								<option value="Choose Brand">-select role-</option>
							</select>
						</div>
					</div>

					<div class="form-group">
						<label class="col-md-4 control-label">Description</label>
						<div class="col-md-4">
							<input type="text" class="form-control" placeholder="Enter Description">
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-4 control-label">Size</label>
						<div class="col-md-4">
							<input type="text" class="form-control" placeholder="Enter Size">
						</div>
					</div>

				</div>
				<div class="form-group">
					<label class="col-md-4 control-label">Weight</label>
					<div class="col-md-4">
						<input type="text" class="form-control" placeholder="Enter Weight">
					</div>
				</div>


				<div class="form-group">
					<label class="col-md-4 control-label">Unit of Measurement</label>
					<div class="col-md-4">
						<select class="select_role form-control" data-placeholder="Choose a Role" tabindex="1">
							<option value="Choose Role">-select role-</option>
						</select>
					</div>
				</div>


				
				<div class="form-group">
					<label class="col-md-4 control-label">Status</label>
					<div class="col-md-4">
						<input type="text" class="form-control" placeholder="Enter Status">
					</div>
				</div>

				<div class="form-group">
					<label class="col-md-4 control-label">Supplier</label>
					<div class="col-md-4">
						<select class="select_role form-control" data-placeholder="Choose a Role" tabindex="1">
							<option value="Chito Marketing">Chito Marketing</option>
						</select>
					</div>
				</div>

				
				
				<div class="form-actions fluid">
					<div class="col-md-offset-3 col-md-9">
						<button type="submit" class="btn blue">Submit</button>
						<button type="button" class="btn default">Cancel</button>
					</div>
				</div>
				
				<!-- END FORM-->
			</form>
		</div>
	</div>
</div>
