<table class="table">
 <tr>
 <th>Code</th>
 <th>Name</th>
 <th>&nbsp;</th>
 </tr>
 <?php foreach ($products as $product) : ?>
	 <tr>
	 <td><?php echo $this->escapeHtml($product->code);?></td>
	 <td><?php echo $this->escapeHtml($product->name);?></td>
	 <td>
	 	<a href="<?php echo $this->url('product_edit',array('action'=>'edit', 'id' => $product->id));?>">Edit</a>
	 	<a href="<?php echo $this->url('product_del',array('action'=>'delete', 'id' => $product->id));?>">Delete</a>
	 </td>
	 </tr>
 <?php endforeach; ?>
</table>
