
<div class="tab-pane active" id="tab_0">
	<div class="portlet box green">
		<div class="portlet-title">
			<div class="caption">
				<i class="fa fa-reorder"></i>Add New user
			</div>
			<div class="tools">
				<a href="javascript:;" class="collapse">
				</a>
				<a href="#portlet-config" data-toggle="modal" class="config">
				</a>
				<a href="javascript:;" class="reload">
				</a>
				<a href="javascript:;" class="remove">
				</a>
			</div>
		</div>
		<div class="portlet-body form">
		<!-- BEGIN FORM-->
			<form action="#" class="form-horizontal">
				<div class="form-body">
					<div class="form-group">
						<label class="col-md-4 control-label">First Name</label>
						<div class="col-md-4">
							<input type="text" class="form-control" placeholder="Enter First Name">
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-4 control-label">Middle Name</label>
						<div class="col-md-4">
							<input type="text" class="form-control" placeholder="Enter Middle Name">
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-4 control-label">Last Name</label>
							<div class="col-md-4">
								<input type="text" class="form-control" placeholder="Enter Last Name">
							</div>
					</div>
					<div class="form-group">
						<label class="col-md-4 control-label">Email Address</label>
							<div class="col-md-4">
								<div class="input-group">
									<span class="input-group-addon">
										<i class="fa fa-envelope"></i>
									</span>
										<input type="email" class="form-control" placeholder="Email Address">
								</div>
							</div>
					</div>
					<div class="form-group">
						<label class="col-md-4 control-label">Role</label>
							<div class="col-md-4">
								<select class="select_role form-control" data-placeholder="Choose a Role" tabindex="1">
									<option value="Choose Role">-select role-</option>
								</select>
							</div>
					</div>
					<div class="form-group">
						<label class="col-md-4 control-label">Password</label>
							<div class="col-md-4">
								<div class="input-group">
									<input type="password" class="form-control" placeholder="Password">
										<span class="input-group-addon">
											<i class="fa fa-user"></i>
										</span>
								</div>
							</div>
					</div>
												
					<div class="form-group">
							<label class="col-md-4 control-label">Confirm Password</label>
								<div class="col-md-4">
									<div class="input-group">
											<input type="password" class="form-control" placeholder="Confirm Password">
												<span class="input-group-addon">
													<i class="fa fa-user"></i>
												</span>
									</div>
							</div>
					</div>
					<div class="form-actions fluid">
						<div class="col-md-offset-3 col-md-9">
							<button type="submit" class="btn blue">Submit</button>
								<button type="button" class="btn default">Cancel</button>
						</div>
					</div>
			</form>
										<!-- END FORM-->
			</div>
		</div>
</div>
