 <?php
 $form->setAttribute('action', $this->url('user_edit', array('action' => 'edit', 'id' => $this->id)));
 $form->setAttribute('class', 'form-horizontal');
 $form->prepare();
 ?>
<div class="tab-pane active" id="tab_0">
	<div class="portlet box green">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-reorder"></i>Edit user
				</div>
				<div class="tools">
					<a href="javascript:;" class="collapse"></a>
					<a href="#portlet-config" data-toggle="modal" class="config"></a>
					<a href="javascript:;" class="reload"></a>
					<a href="javascript:;" class="remove"></a>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<?php echo $this->form()->openTag($form); ?>
				
					<div class="form-body">
						<div class="form-group">
							<label class="col-md-4 control-label">First Name</label>
							<div class="col-md-4">
								<?php  echo $this->formRow($form->get('fname')); ?>
							</div>
						</div>
						<div class="form-group">
							<label class="col-md-4 control-label">Middle Name</label>
							<div class="col-md-4">
								<?php  echo $this->formRow($form->get('mname')); ?>
							</div>
						</div>
						<div class="form-group">
							<label class="col-md-4 control-label">Last Name</label>
							<div class="col-md-4">
								<?php  echo $this->formRow($form->get('lname')); ?>
							</div>
						</div>
						<div class="form-group">
							<label class="col-md-4 control-label">Email Address</label>
							<div class="col-md-4">
								<div class="input-group">
									<span class="input-group-addon">
										<i class="fa fa-envelope"></i>
									</span>
									<?php  echo $this->formRow($form->get('email')); ?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="col-md-4 control-label">Role</label>
							<div class="col-md-4">
								<?php  echo $this->formRow($form->get('role_id')); ?>
							</div>
						</div>
						<div class="form-group">
							<label class="col-md-4 control-label">Password</label>
							<div class="col-md-4">
								<?php  echo $this->formRow($form->get('key')); ?>
							</div>
						</div>
						<div class="form-group">
							<label class="col-md-4 control-label">Confirm Password</label>
							<div class="col-md-4">
								<?php  echo $this->formRow($form->get('secret')); ?>
							</div>
						</div>
						<div class="form-actions fluid">
							<div class="col-md-offset-3 col-md-9">
							<?php  echo $this->formRow($form->get('submit')); ?>
							
								<button type="button" class="btn default">Cancel</button>
							</div>
						</div>
				<?php echo $this->form()->closeTag(); ?>
				<!-- END FORM-->
			</div>
	</div>
</div>