<table class="table">
 <tr>
 <th>Title</th>
 <th>Artist</th>
 <th>&nbsp;</th>
 </tr>
 <?php foreach ($users as $user) : ?>
	 <tr>
	 <td><?php echo $this->escapeHtml($user->fname);?></td>
	 <td><?php echo $this->escapeHtml($user->lname);?></td>
	 <td>
	 	<a href="<?php echo $this->url('user_edit',array('action'=>'edit', 'id' => $user->id));?>">Edit</a>
	 	<a href="<?php echo $this->url('user_del',array('action'=>'delete', 'id' => $user->id));?>">Delete</a>
	 </td>
	 </tr>
 <?php endforeach; ?>
</table>
