 <?php
 $form->setAttribute('action', $this->url('user_add', array('action' => 'add')));
 $form->setAttribute('class', 'form-horizontal');
 $form->prepare();
 ?>
<div class="tab-pane active" id="tab_0">
	<div class="portlet box green">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-reorder"></i>Add New user
				</div>
				<div class="tools">
					<a href="javascript:;" class="collapse"></a>
					<a href="#portlet-config" data-toggle="modal" class="config"></a>
					<a href="javascript:;" class="reload"></a>
					<a href="javascript:;" class="remove"></a>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<?php echo $this->form()->openTag($form); ?>
				
				<div class="form-body">
					<div class="form-group">
						<label class="col-md-2 control-label">SONO</label>
						<div class="col-md-3">
								<?php  echo $this->formRow($form->get('sono')); ?>
						</div>
						<label class="col-md-2 control-label">Customer</label>
						<div class="col-md-3">
								<?php  echo $this->formRow($form->get('customer')); ?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-2 control-label">Transaction Type</label>
						<div class="col-md-3">
								<?php  echo $this->formRow($form->get('transtype')); ?>
						</div>
						<label class="col-md-2 control-label">Ship To</label>
						<div class="col-md-3">
								<?php  echo $this->formRow($form->get('shipto')); ?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-2 control-label">Bill To</label>
						<div class="col-md-3">
								<?php  echo $this->formRow($form->get('billto')); ?>
						</div>
						<label class="col-md-2 control-label">Order Source</label>
						<div class="col-md-3">
								<?php  echo $this->formRow($form->get('ordersrc')); ?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-2 control-label">SE</label>
						<div class="col-md-3">
								<?php  echo $this->formRow($form->get('se')); ?>
						</div>
						<label class="col-md-2 control-label">SM</label>
						<div class="col-md-3">
								<?php  echo $this->formRow($form->get('sm')); ?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-2 control-label">Terms</label>
						<div class="col-md-3">
								<?php  echo $this->formRow($form->get('terms')); ?>
						</div>
						<label class="col-md-2 control-label">PONO</label>
						<div class="col-md-3">
								<?php  echo $this->formRow($form->get('pono')); ?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-2 control-label">Prefered Delivery Date</label>
						<div class="col-md-3">
								<?php  echo $this->formRow($form->get('prefdeldate')); ?>
						</div>
						<label class="col-md-2 control-label">Ordered By</label>
						<div class="col-md-3">
								<?php  echo $this->formRow($form->get('orderedby')); ?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-2 control-label">Actual Delivery Date</label>
						<div class="col-md-3">
								<?php  echo $this->formRow($form->get('actdeldate')); ?>
						</div>
						<label class="col-md-2 control-label">Notes</label>
						<div class="col-md-3">
								<?php  echo $this->formRow($form->get('notes')); ?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-2 control-label">Status</label>
						<div class="col-md-3">
								<?php  echo $this->formRow($form->get('status')); ?>
						</div>
					</div>
						<div class="form-actions fluid">
							<div class="col-md-offset-3 col-md-9">
							<?php  echo $this->formRow($form->get('submit')); ?>
							
								<button type="button" class="btn default">Cancel</button>
							</div>
						</div>
				<?php echo $this->form()->closeTag(); ?>
				<!-- END FORM-->
			</div>
	</div>
</div>