
<div class="tab-pane active" id="tab_0">
		<div class="portlet box green">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-reorder"></i>Add New Customer
				</div>
				<div class="tools">
					<a href="javascript:;" class="collapse"></a>
					<a href="#portlet-config" data-toggle="modal" class="config"></a>
					<a href="javascript:;" class="reload"></a>
					<a href="javascript:;" class="remove"></a>
			</div>
		</div>
		<div class="portlet-body form">
			<!-- BEGIN FORM-->
			<form action="#" class="form-horizontal">
				<div class="form-body">
			<h3 class="form-section">Customer Profile</h3>				
					<div class="form-group">
						<label class="col-md-2 control-label">Category</label>
						<div class="col-md-3">
							<select class="select_role form-control" data-placeholder="Choose Category" tabindex="1">
								<?php  echo $this->formRow($form->get('category')); ?>
							</select>
						</div>
						<label class="col-md-2 control-label">Type</label>
						<div class="col-md-3">
							<select class="select_type form-control" data-placeholder="Choose Category" tabindex="1">
								<?php  echo $this->formRow($form->get('type')); ?>
							</select>
						</div>
					</div>
				
					<div class="form-group">
						<label class="col-md-2 control-label">Owner Name</label>
						<div class="col-md-3">
							<?php  echo $this->formRow($form->get('owner')); ?>
						</div>
						<label class="col-md-2 control-label">Company Name</label>
						<div class="col-md-3">
							<?php  echo $this->formRow($form->get('name')); ?>
						</div>
					</div>
					
					<div class="form-group">
						<label class="col-md-2 control-label">Trade Name</label>
						<div class="col-md-3">
							<?php  echo $this->formRow($form->get('trade_name')); ?>
						</div>
						<label class="col-md-2 control-label">Consignee</label>
						<div class="col-md-3">
							<?php  echo $this->formRow($form->get('consignee')); ?>
						</div>
					
					</div>
					<div class="form-group">
				
						<label class="col-md-2 control-label">Phone</label>
						<div class="col-md-3">
							<?php  echo $this->formRow($form->get('phone')); ?>
						</div>
						<label class="col-md-2 control-label">Website</label>
						<div class="col-md-3">
							<?php  echo $this->formRow($form->get('website')); ?>
						</div>
					</div>
					<div class="form-group">
					<label class="col-md-2 control-label">Email Address</label>
							<div class="col-md-3">
								<div class="input-group">
									<span class="input-group-addon">
										<i class="fa fa-envelope"></i>
									</span>
									<?php  echo $this->formRow($form->get('email')); ?>
								</div>
							</div>
						<label class="col-md-2 control-label">TIN</label>
						<div class="col-md-3">
							<?php  echo $this->formRow($form->get('tin')); ?>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-2 control-label">Unpaid Invoice</label>
						<div class="col-md-3">
							<?php  echo $this->formRow($form->get('unpaid_invoice')); ?>
						</div>
						<label class="col-md-2 control-label">Allow Credit</label>
						<div class="col-md-3"> 
							<?php  echo $this->formRow($form->get('allow_credit')); ?>
						</div>
					</div>
					
					<div class="form-group">
							<label class="col-md-2 control-label">Payment Terms</label>
						<div class="col-md-3">
							<?php  echo $this->formRow($form->get('payment_terms')); ?>
						</div>
						
					<label class="col-md-2 control-label">Preferred Shipping Mode</label>
						<div class="col-md-3">
						<?php  echo $this->formRow($form->get('shipping_mode')); ?>
						</div>
					</div>
					
					<div class="form-group">
						<label class="col-md-2 control-label">Assigned SE</label>
						<div class="col-md-3">
							<?php  echo $this->formRow($form->get('sales_executive')); ?>
						</div>
						
						<label class="col-md-2 control-label">Status</label>
						<div class="col-md-3">
							<?php  echo $this->formRow($form->get('status')); ?>
						</div>
					</div>

	<!--Customer Profile End-->
	<!--Customer Shipping Address Start-->
	<h3 class="form-section">Shipping Address</h3>
		<div class ="container">
		<div class="row">
			<div class="col-md-11 ">
				<div class="form-group">
					<label>Street</label>
							<?php  echo $this->formRow($form->get('street')); ?>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-5">
				<div class="form-group">
					
						<label>City</label>
							<?php  echo $this->formRow($form->get('city')); ?>
				</div>
		</div>
			<!--/span-->
		<div class="col-md-offset-1 col-md-5">
			<div class="form-group">
				<label>Province</label>
					<?php  echo $this->formRow($form->get('province')); ?>
			</div>
		</div>
		<!--/span-->
		
			<!--/row-->
		
				<div class="col-md-5">
					<div class="form-group">
						<label>Zip Code</label>
							<?php  echo $this->formRow($form->get('zipcode')); ?>
					</div>
				</div>			
							<!--/span-->
				
			</div>
			
		</div>
	
	<!--Customer Shipping Address End-->
	<!--Customer Billing Address Start-->
	<h3 class="form-section">Billing Address</h3>
			<div class ="container">
				<div class="row">
					<div class="col-md-11 ">
						<div class="form-group">
							<label>Street</label>
							<?php  echo $this->formRow($form->get('street')); ?>
						</div>
					</div>
				</div>
		<div class="row">
			<div class="col-md-5">
				<div class="form-group">
					
						<label>City</label>
							<?php  echo $this->formRow($form->get('city')); ?>
						
				</div>
			</div>
			<div class="col-md-offset-1 col-md-5">
				<div class="form-group">
					
						<label>Province</label>
							<?php  echo $this->formRow($form->get('province')); ?>
				</div>
			</div>
		</div>
			<!--/span-->
		<div class="row">
			<div class="col-md-5">
				<div class="form-group">
					
						<label>Zip Code</label>
							<?php  echo $this->formRow($form->get('zipcode')); ?>
				</div>
			</div>
		</div>
	</div>
	<!--Customer Billing Address End-->
	
	
	
				<div class="form-actions fluid">
					<div class="col-md-offset-5 col-md-6">
						<button type="submit" class="btn blue">Submit</button>
						<button type="button" class="btn default">Cancel</button>
					</div>
				</div>
				
				<!-- END FORM-->
			</form>
		</div>
</div>	