<?php
$form->setAttribute('action', $this->url('customer_delete', array('action' => 'del')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>

<div class="tab-pane active" id="tab_0">
    <div class="portlet box green">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-reorder"></i>Add New Customer
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse">
                </a>
                <a href="#portlet-config" data-toggle="modal" class="config">
                </a>
                <a href="javascript:;" class="reload">
                </a>
                <a href="javascript:;" class="remove">
                </a>
            </div>
        </div>
        <div class="portlet-body form">
            <!-- BEGIN FORM-->
            <?php echo $this->form()->openTag($form); ?>

            <div class="form-body">
                <div class="form-group">
                    <label class="col-md-4 control-label">Category</label>
                    <div class="col-md-4">
                        <!--							<input type="text" class="form-control" placeholder="Enter Code">-->
                        <?php  echo $this->formRow($form->get('category')); ?>

                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 control-label">Type</label>
                    <div class="col-md-4">
                        <?php  echo $this->formRow($form->get('type')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label">Name</label>
                    <div class="col-md-4">
                        <?php  echo $this->formRow($form->get('name')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label">Consignee</label>
                    <div class="col-md-4">
                        <?php  echo $this->formRow($form->get('consignee')); ?>

                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label">Branch</label>
                    <div class="col-md-4">
                        <?php  echo $this->formRow($form->get('branch')); ?>

                        <!--							<input type="text" class="form-control" placeholder="Enter Description">-->
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 control-label">Trade Name</label>
                    <div class="col-md-4">
                        <?php  echo $this->formRow($form->get('trade_name')); ?>
                    </div>
                </div>

            </div>
            <div class="form-group">
                <label class="col-md-4 control-label">Phone Number</label>
                <div class="col-md-4">
                    <?php  echo $this->formRow($form->get('phone')); ?>
                </div>
            </div>


            <div class="form-group">
                <label class="col-md-4 control-label">Email</label>
                <div class="col-md-4">
                    <?php  echo $this->formRow($form->get('email')); ?>
                </div>
            </div>


            <div class="form-group">
                <label class="col-md-4 control-label">T.I.N. </label>
                <div class="col-md-4">
                    <?php  echo $this->formRow($form->get('tin')); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4 control-label">Status</label>
                <div class="col-md-4">
                    <?php  echo $this->formRow($form->get('status')); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4 control-label">Remarks</label>
                <div class="col-md-4">
                    <input type="text" class="form-control" placeholder="Enter Your Remarks Here" required>
                </div>
            </div>


            <div class="form-actions fluid">
                <div class="col-md-offset-3 col-md-9">
                    <?php  echo $this->formRow($form->get('submit')); ?>
                    <button type="button" class="btn default">Cancel</button>
                </div>
            </div>

            <!-- END FORM-->
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</div>
