<div class="tab-pane active" id="tab_0">
		<div class="portlet box green">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-reorder"></i>Add New Customer
				</div>
				<div class="tools">
					<a href="javascript:;" class="collapse"></a>
					<a href="#portlet-config" data-toggle="modal" class="config"></a>
					<a href="javascript:;" class="reload"></a>
					<a href="javascript:;" class="remove"></a>
			</div>
		</div>
		<div class="portlet-body form">
			<!-- BEGIN FORM-->
			<form action="#" class="form-horizontal">
				<div class="form-body">
			<h3 class="form-section">Customer Profile</h3>				
					<div class="form-group">
						<label class="col-md-2 control-label">Category</label>
						<div class="col-md-3">
							<select class="select_role form-control" data-placeholder="Choose Category" tabindex="1">
								<?php  echo $this->formRow($form->get('category')); ?>
							</select>
						</div>
						<label class="col-md-2 control-label">Type</label>
						<div class="col-md-3">
							<select class="select_role form-control" data-placeholder="Choose Category" tabindex="1">
								<?php  echo $this->formRow($form->get('category')); ?>
							</select>
						</div>
					</div>
				
					<div class="form-group">
						<label class="col-md-2 control-label">Owner Name</label>
						<div class="col-md-3">
							<input type="text" class="form-control" placeholder="Enter Owner Name">
						</div>
						<label class="col-md-2 control-label">Company Name</label>
						<div class="col-md-3">
							<input type="text" class="form-control" placeholder="Enter Company Name">
						</div>
					</div>
					
					<div class="form-group">
						<label class="col-md-2 control-label">Trade Name</label>
						<div class="col-md-3">
							<input type="text" class="form-control" placeholder="Enter Trade Name">
						</div>
						<label class="col-md-2 control-label">Consignee</label>
						<div class="col-md-3">
							<select class="select_consignor form-control" data-placeholder="" tabindex="1">
								<option value="Yes">No</option>
								<option value="No">Yes</option>
							</select>
						</div>
					
					</div>
					<div class="form-group">
				
						<label class="col-md-2 control-label">Phone</label>
						<div class="col-md-3">
							<input type="text" class="form-control" placeholder="Enter Phone Number">
						</div>
						<label class="col-md-2 control-label">Website</label>
						<div class="col-md-3">
							<input type="text" class="form-control" placeholder="Enter Website">
						</div>
					</div>
					<div class="form-group">
					<label class="col-md-2 control-label">Email Address</label>
							<div class="col-md-3">
								<div class="input-group">
									<span class="input-group-addon">
										<i class="fa fa-envelope"></i>
									</span>
									<input type="text" class="form-control" placeholder="Enter Email Address">
								</div>
							</div>
						<label class="col-md-2 control-label">TIN</label>
						<div class="col-md-3">
							<input type="text" class="form-control" placeholder="Enter Company TIN">
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-2 control-label">Unpaid Invoice</label>
						<div class="col-md-3">
							<input type="text" class="form-control" placeholder="Enter Unpaid Invoice">
						</div>
						<label class="col-md-2 control-label">Allow Credit</label>
						<div class="col-md-3">
							<select class="select_role form-control" data-placeholder="------" tabindex="0">
								<option value="No">No</option>
								<option value="Yes">Yes</option>
							</select>
						</div>
					</div>
					
					<div class="form-group">
							<label class="col-md-2 control-label">Payment Terms</label>
						<div class="col-md-3">
							<select class="select_role form-control" data-placeholder="Select Terms" tabindex="1">
								<option value="Yes">COD</option>
								<option value="No">30 Days</option>
								<option value="No">15 Days</option>
							</select>
						</div>
						
					<label class="col-md-2 control-label">Preferred Shipping Mode</label>
						<div class="col-md-3">
							<select class="select_role form-control" data-placeholder="Select Mode" tabindex="0">
								<option value="Select Mode">Select Mode</option>
							</select>
						</div>
					</div>
					
					<div class="form-group">
						<label class="col-md-2 control-label">Assigned SE</label>
						<div class="col-md-3">
							<select class="select_role form-control" data-placeholder="Select SE" tabindex="0">
								<option value="1">Select SE</option>
								
							</select>
						</div>
						
						<label class="col-md-2 control-label">Status</label>
						<div class="col-md-3">
							<select class="select_role form-control" data-placeholder="Select Status" tabindex="0">
								<option value="1">Select Status</option>
								
							</select>
						</div>
					</div>

	<!--Customer Profile End-->
	<!--Customer Shipping Address Start-->
	<h3 class="form-section">Shipping Address</h3>
		<div class ="container">
		<div class="row">
			<div class="col-md-11 ">
				<div class="form-group">
					<label>Street</label>
						<input type="text" class="form-control">
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-5">
				<div class="form-group">
					
						<label>City</label>
						<select class="form-control">
						</select>
					
				</div>
		</div>
			<!--/span-->
		<div class="col-md-offset-1 col-md-5">
			<div class="form-group">
				<label>Province</label>
				<select class="form-control"></select>
			</div>
		</div>
		<!--/span-->
		
			<!--/row-->
		
				<div class="col-md-5">
					<div class="form-group">
						<label>Post Code</label>
						<input type="text" class="form-control">
					</div>
				</div>			
							<!--/span-->
				<div class="col-md-offset-1 col-md-5">
					<div class="form-group">
						<label>Country</label>
						<select class="form-control">
						</select>
					</div>
				</div>
			</div>
			
		</div>
	
	<!--Customer Shipping Address End-->
	<!--Customer Billing Address Start-->
	<h3 class="form-section">Billing Address</h3>
			<div class ="container">
				<div class="row">
					<div class="col-md-11 ">
						<div class="form-group">
							<label>Street</label>
						<input type="text" class="form-control">
						</div>
					</div>
				</div>
		<div class="row">
			<div class="col-md-5">
				<div class="form-group">
					
						<label>City</label>
						<select class="form-control">
						</select>
				</div>
			</div>
			<div class="col-md-offset-1 col-md-5">
				<div class="form-group">
					
						<label>Province</label>
						<select class="form-control">
						</select>
				</div>
			</div>
		</div>
			<!--/span-->
		<div class="row">
			<div class="col-md-5">
				<div class="form-group">
					
						<label>Zip Code</label>
						<input type="text" class="form-control">
				</div>
			</div>
			<div class="col-md-offset-1 col-md-5">
				<div class="form-group">
					
						<label>Country</label>
						<select class="form-control">
						</select>
					</div>
				</div>
			</div>
			<!--/row-->
					
			
		</div>
	</div>
	<!--Customer Billing Address End-->
	
	
	
				<div class="form-actions fluid">
					<div class="col-md-offset-5 col-md-6">
						<button type="submit" class="btn blue">Submit</button>
						<button type="button" class="btn default">Cancel</button>
					</div>
				</div>
				
				<!-- END FORM-->
			</form>
		</div>
</div>	