				 
<div class="tab-pane active" id="tab_0">
	<div class="portlet box green">
		<div class="portlet-title">
			<div class="caption">
				<i class="fa fa-reorder"></i>Add New Customer
			</div>
			<div class="tools">
				<a href="javascript:;" class="collapse">
				</a>
				<a href="#portlet-config" data-toggle="modal" class="config">
				</a>
				<a href="javascript:;" class="reload">
				</a>
				<a href="javascript:;" class="remove">
				</a>
			</div>
		</div>
		<div class="portlet-body form">
			<!-- BEGIN FORM-->
			<form action="#" class="form-horizontal">
				<div class="form-body">
				
					<div class="form-group">
						<label class="col-md-2 control-label">Category</label>
						<div class="col-md-3">
							<select class="select_role form-control" data-placeholder="Choose Category" tabindex="1">
								<option value="Choose UOM">Select Category-</option>
							</select>
						</div>
						<label class="col-md-2 control-label">Type</label>
						<div class="col-md-3">
							<select class="select_role form-control" data-placeholder="Choose Category" tabindex="1">
								<option value="Choose UOM">Select Type-</option>
							</select>
						</div>
					</div>
				
					<div class="form-group">
						<label class="col-md-2 control-label">Owner Name</label>
						<div class="col-md-3">
							<input type="text" class="form-control" placeholder="Enter Owner Name">
						</div>
						<label class="col-md-2 control-label">Company Name</label>
						<div class="col-md-3">
							<input type="text" class="form-control" placeholder="Enter Company Name">
						</div>
					</div>
					
					
					
					<div class="form-group">
						<label class="col-md-2 control-label">Consignor</label>
						<div class="col-md-3">
							<select class="select_consignor form-control" data-placeholder="" tabindex="1">
								<option value="Yes">No</option>
								<option value="No">Yes</option>
							</select>
						</div>
						<label class="col-md-2 control-label">Branch</label>
						<div class="col-md-3">
							<input type="text" class="form-control" placeholder="Enter Branch">
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-2 control-label">Franchise</label>
						<div class="col-md-3">
							<select class="select_role form-control" data-placeholder="Choose Category" tabindex="1">
								<option value="Yes">No</option>
								<option value="No">Yes</option>
							</select>
						</div>
						<label class="col-md-2 control-label">Phone</label>
						<div class="col-md-3">
							<input type="text" class="form-control" placeholder="Enter Phone Number">
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-2 control-label">Trade Name</label>
						<div class="col-md-3">
							<input type="text" class="form-control" placeholder="Enter Trade Name">
						</div>
						<label class="col-md-2 control-label">TIN</label>
						<div class="col-md-3">
							<input type="text" class="form-control" placeholder="Enter Company TIN">
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-2 control-label">Website</label>
						<div class="col-md-3">
							<input type="text" class="form-control" placeholder="Enter Website">
						</div>
						<label class="col-md-2 control-label">Email Address</label>
							<div class="col-md-3">
								<div class="input-group">
									<span class="input-group-addon">
										<i class="fa fa-envelope"></i>
									</span>
									<input type="text" class="form-control" placeholder="Enter Email Address">
								</div>
							</div>
					</div>
					<div class="form-group">
						<label class="col-md-2 control-label">Allow Credit</label>
						<div class="col-md-3">
							<select class="select_role form-control" data-placeholder="------" tabindex="0">
								<option value="No">No</option>
								<option value="Yes">Yes</option>
							</select>
						</div>
						<label class="col-md-2 control-label">Payment Terms</label>
						<div class="col-md-3">
							<select class="select_role form-control" data-placeholder="Select Terms" tabindex="1">
								<option value="Yes">COD</option>
								<option value="No">30 Days</option>
								<option value="No">15 Days</option>
							</select>
						</div>
					</div>
					<div class="form-group">
						<label class="col-md-2 control-label">Preferred Shipping Mode</label>
						<div class="col-md-3">
							<select class="select_role form-control" data-placeholder="Select Mode" tabindex="0">
								<option value="Select Mode">Select Mode</option>
							</select>
						</div>
						<label class="col-md-2 control-label">Price Type</label>
						<div class="col-md-3">
							<select class="select_role form-control" data-placeholder="Select Terms" tabindex="1">
								<option value="PriceType">Select Price Type</option>
								
							</select>
						</div>
					</div>
					<div class="form-group">
				
						<label class="col-md-2 control-label">Assigned SE</label>
						<div class="col-md-3">
							<select class="select_role form-control" data-placeholder="Select SE" tabindex="0">
								<option value="1">Select SE</option>
								
							</select>
						</div>
						<label class="col-md-2 control-label">Status</label>
						<div class="col-md-3">
							<select class="select_role form-control" data-placeholder="Select Status" tabindex="0">
								<option value="1">Select Status</option>
								
							</select>
						</div>
					</div>
				<div class="form-actions fluid">
					<div class="col-md-offset-5 col-md-6">
						<button type="submit" class="btn blue">Submit</button>
						<button type="button" class="btn default">Cancel</button>
					</div>
				</div>
				
				<!-- END FORM-->
			</form>
		</div>
	</div>
</div>
