<table class="table">
    <tr>
        <th>Category</th>
        <th>Type</th>
        <th>Name</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($customers as $customer) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($customer->category);?></td>
            <td><?php echo $this->escapeHtml($customer->type);?></td>
            <td><?php echo $this->escapeHtml($customer->name);?></td>
            <td>
                <a href="<?php echo $this->url('customer_edit',array('action'=>'edit', 'id' => $customer->id));?>">Edit</a>
                <a href="<?php echo $this->url('customer_del',array('action'=>'del', 'id' => $customer->id));?>">Delete</a>
            </td>

        </tr>
    <?php endforeach; ?>
</table>
