<table class="table">
 <tr>
 <th>customer_category</th>
 <th>customer_name</th>
 <th>&nbsp;</th>
 </tr>
 <?php foreach ($customers as $customer) : ?>
	 <tr>
	 <td><?php echo $this->escapeHtml($customer->customer_category);?></td>
	 <td><?php echo $this->escapeHtml($customer->customer_name);?></td>
	 <td>
	 	<a href="<?php echo $this->url('customer_edit',array('action'=>'edit', 'id' => $customer->id));?>">Edit</a>
	 	<a href="<?php echo $this->url('customer_del',array('action'=>'delete', 'id' => $customer->id));?>">Delete</a>
	 </td>
	 </tr>
 <?php endforeach; ?>
</table>
