<table class="table">
 <tr>
 <th>Type</th>
 <th>Name</th>
 <th>&nbsp;</th>
 </tr>
 <?php foreach ($customers as $customer) : ?>
	 <tr>
	 <td><?php echo $this->escapeHtml($customer->code);?></td>
	 <td><?php echo $this->escapeHtml($customer->name);?></td>
	 <td>
	 	<a href="<?php echo $this->url('product_edit',array('action'=>'edit', 'id' => $customer->id));?>">Edit</a>
	 	<a href="<?php echo $this->url('product_del',array('action'=>'delete', 'id' => $customer->id));?>">Delete</a>
	 </td>
	 </tr>
 <?php endforeach; ?>
</table>
